### PR TITLE
Move AUMID to LaunchOptions

### PR DESCRIPTION
**Pull request by FlaminSarge**
Also add empty Devkit/DevkitGameID

Also: remove old setup.aiproj reference and the portable zip (since Release.zip is now on the latest release)

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Do I need to bump version to 26.0.0.1?

**Comment by FlaminSarge** [comment]
For the failure, Appveyor settings need `nuget restore` in `Before build script`

**Comment by FlaminSarge** [comment]
@BrianLima do any other changes need to go into this PR?

**Comment by BrianLima** [comment]
Hi @FlaminSarge thanks, I'll be reviewing these tomorrow, ok?

**Pull request merged**
