### PR TITLE
Add Support for Long Paths Closes #62

### LINKED ISSUE #62: The specified path, file name, or both are too long....... For all yakuza games
not sure if a fix is even possible, however would like you to be aware of this issue.

the current length of the average yakuza game folder is as follows: SEGAofAmericaInc.Yakuza3PC_s751p9cej88mt
full path is as follows: C:\Users\[USERNAME]\AppData\Local\Packages

extra information: 
length of average yakuza game executable folder: SEGAofAmericaInc.Yakuza3PC_1.0.20.0_x64__s751p9cej88mt
full path to executable: C:\Program Files\WindowsApps\SEGAofAmericaInc.Yakuza3PC_1.0.20.0_x64__s751p9cej88mt

### PR DESCRIPTION
**Pull request by Camology**
Sorry about the messy commit history, I do not use Visual Studio and everything got completely fucked. Small change, only have to update the app.config as noted here:
https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/net-4-6-2-and-long-paths-on-windows-10

Closes #62  which I came here trying to figure out for the Yakuza games as well.

### CODE REVIEW

**Comment by BrianLima** [comment]
Hey, this looks great, did not know about this setting, and couldn't reproduce on my side so i was a little bit lost with this bug, Thanks for the PR!

**Comment by Camology** [comment]
No problem @BrianLima  and thanks for the quick response. I am having some other issues that I think might be related to Windows 11, might open an issue but what all information would you want me to include on it as far as debug/logging info?

The issue I am having is that I can add titles from Gamepass no problem to Steam, they show up, etc. But when I try to play anything I hear the game start on my host PC via remote play, but the client PC just closes it out. The game does launch properly on my host PC and keeps playing though. Maybe I misunderstood this project, does it not work with Remote play, or is it maybe some sort of Windows 11 issue? Thought it was the file length issue thats why I fixed this bug :p

**Comment by BrianLima** [comment]
If you enable the streaming mode in the settings, the app tries to enlarge it's window and wait for steam to start streaming. It might not actually work since steam does not see UWPHook as an usual game and more like a desktop application (which it is) causing it to not send controller inputs properly to the host computer, converting the controller buttons to mouse and keyboard inputs. Some people suggest using VirtualHere for remote streaming controller games, essentially i'm tricking Steam into streaming the whole desktop.
I should probably try to figure out a better way to support streaming gamepass games but i have not caught wind of any newer methods...

**Comment by Camology** [comment]
Huh, I didnt even see that streaming option. Redid the games with the streaming option, it definitely goes further but still crashes eventually on the client PC. I will check out VirtualHere though, mostly want to play some gamepass games in my living room without buying a very long HDMI :p

**Comment by BrianLima** [comment]
Hope you get it working! Your PR has been published @ v2.9.2 https://github.com/BrianLima/UWPHook/releases/tag/2.9.2

**Pull request merged**
